export const ApiDownloadComponent = {
  apiDownBgColor: "apidownbgcolor.main",
  bgImg1: "url('/img/img_bottom_phone_00@2x.png')",
  bgImg2: "url('/img/img_bottom_phone_01@2x.png')",
  bgImg3: "url('/img/img_bottom_phone_02@2x.png')",
  bgMobileImg1: "./img/img_bottom_mockup1@2x.png",
  bgMobileImg2: "./img/img_bottom_mockup2@2x.png",
  bgMobileImg3: "./img/img_bottom_mockup3@2x.png",
  ssamtakManualColor1: "irangtalk",
  ssamtakManualColor2: "ssamtalk",
  ssamtakManualColor3: "rangtalk",
  apiDownloadTitleColor1: "irangtalk.main",
  apiDownloadTitleColor2: "ssamtalk.main",
  apiDownloadTitleColor3: "rangtalk.main",
  apiDownloadTitle1: "",
  apiDownloadTitle2: "쌤이랑톡",
  apiDownloadTitle3: "학교랑톡",
  ssamtakManualExplain1: ["우리아이 등하굣길 안심",<br/> ,"알림서비스"],
  ssamtakManualExplain2: "아이와 학부모를 위한 양방향 소통앱 쌤이랑톡 입니다.",
  ssamtakManualExplain3: "학교와 선생님을 위한 양방향 소통앱 학교랑톡입니다.",
  ssamtakManual1: "아이랑톡메뉴얼다운로드",
  ssamtakManual2: "쌤톡메뉴얼다운로드",
  ssamtakManual3: "랑톡메뉴얼다운로드",
  imgBottomLogo1: "./img/아이랑톡2@2x.png",
  imgBottomLogo2: "./img/img_bottom_logo_2@2x.png",
  imgBottomLogo3: "./img/img_bottom_logo_3@2x.png",
  ssamtakManualColor: "ssamtalk",
  rangMenual:"url('./downloadfile/KT_학교랑톡_사용자_매뉴얼_V1.4_20210813.pdf')",
  ssamMenual:"url('./downloadfile/KT_쌤이랑톡_사용자_매뉴얼_V1.4_20210813.pdf')",
};
